# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f142ffd66eca8d13ab74b75a192fefc150043552fd8bb9470646fcffb888aa25f885ace47d3645320c06987a7aa53d6067649432fbcb7e32c32e9ccc32a528a7

test:
  secret_key_base: c8559c254077ef59298ccdad9b81f4df6938f293b70bed4ada1031345488db6338c2a978a7739e63ad71305a02bddfb3a76a940ed8617dab2d81f87b004a2195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
